keywords: "'cybersecurity', 'ai', 'ml', 'artificial intelligence', 'machine learning', 'data science',
        'network security', 'threat detection', 'vulnerability assessment', 'intrusion detection',
        'data privacy', 'information assurance', 'algorithm', 'neural networks', 'deep learning',
        'cybersecurity analytics', 'ai security', 'ml security', 'data breaches', 'incident response',
        'risk management', 'cloud security', 'critical infrastructure', 'autonomous systems',
        'predictive analytics', 'anomaly detection', 'behavioral analysis', 'fraud detection', 
        'digital forensics', 'secure ai', 'trustworthy ai', 'explainable ai', 'ethical ai', 'ai ethics',
        'cybersecurity training', 'cybersecurity education', 'ai governance', 'ml governance',
        'data governance', 'zero trust', 'endpoint security', 'application security', 'iot security',
        'operational technology security', 'industrial control systems', 'quantum computing',
        'post-quantum cryptography', 'big data security', 'data loss prevention', 'security automation',
        'security orchestration', 'threat intelligence', 'cyber defense', 'resilience',
        'privacy enhancing technologies', 'federated learning', 'differential privacy'"
llm_model: "gemma3:27b"
number_of_keywords: 50
threshold: 60
forcast: False
